- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Set variables 
#------------------------------------------------------------------------------
  
  # You need to create a file named aws_creds.yaml (update path below) with the following variables:
  #
  #  ec2_access_key: "--your-key-here--"
  #  ec2_secret_key: "--your-secret-here--"
  #
  vars_files:
    - ../../creds/aws_creds.yaml
  
  vars:

  # SSH
    # This is the name of the SSH private key object in AWS
    sshKey: "arch_id_rsa"
    # This is the path to your local SSH private key located on your computer
    sshKeyPath:

  # AWS settings
    
    uk_se_name: arch
    stack_name: ansible-standalone-bigip-demo-1
    aws_region: eu-west-1
    subnet_start: "10.1"
    automation_tool: "ansible"

    vpc_name: "{{ stack_name }}"
    vpc_cidr: "{{ subnet_start }}.0.0/16"
    vpc_subnets:
      mgmt_a:
        cidr: "{{ subnet_start }}.1.0/24"
        az: "{{ aws_region }}a"
      traffic_a:
        cidr: "{{ subnet_start }}.11.0/24"
        az: "{{ aws_region }}a"

    route_id: []



#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

  # Start tasks

  tasks:

  # VPC and Subnets

  - name: GET VPC ID USING TAGS DEFINED DURING AUTOMATED BUILD
    ec2_vpc_net_facts:
      region: "{{ aws_region }}"
      filters:
        "tag:stack": "{{ stack_name }}"
        "tag:UK-SE": "{{ uk_se_name }}"
        "tag:automated": "{{ automation_tool }}"
    register: vpc_facts
  

  - name: OUTPUT VPC ID
    debug:
      msg: "{{ vpc_facts.vpcs[0].vpc_id }}"


  - name: DELETE INTERNET GATEWAY
    ec2_vpc_igw:
      vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      state: absent


  - name: DELETE VPC SUBNETS
    ec2_vpc_subnet:
      vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      cidr: "{{ item.value.cidr }}"
      az: "{{ item.value.az }}"
      state: absent
    with_dict: "{{ vpc_subnets }}"





  - name: DELETE ROUTE TABLE
    ec2_vpc_route_table:
      vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      #route_table_id: "{{ route_id }}"
      tags:
        automated: ansible
        stack: "{{ stack_name }}"
        UK-SE: "{{ uk_se_name }}"
      state: absent


  - name: DELETE VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}" 
      state: absent
      cidr_block: "{{ vpc_cidr }}"
      region: "{{ aws_region }}"
