#------------------------------------------------------------------------------
# Ansible Playbook to Delete Demo Environment
#------------------------------------------------------------------------------
- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Load Variables from files 
#------------------------------------------------------------------------------
  
  # You need to create a file named aws_creds.yaml (update path below) with the following variables:
  #
  #  ec2_access_key: "--your-key-here--"
  #  ec2_secret_key: "--your-secret-here--"
  #
  vars_files:
    - ../../creds/aws_creds.yaml
    - ./vars.yaml
  
#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

#------------------------------------------------------------------------------
# Start Tasks
#------------------------------------------------------------------------------

  tasks:

  - name: DELETE ANSIBLE CFT DEPLOYMENT
    cloudformation:
      stack_name: "{{ stack_name }}"
      state: absent
      region: "{{ aws_region }}"
      disable_rollback: true
      tags:
        automated: "{{ automation_tool }}"
        stack: "{{ stack_name }}"
        UK-SE: "{{ uk_se_name }}"


  - name: GET VPC ID USING TAGS DEFINED DURING AUTOMATED BUILD
    ec2_vpc_net_facts:
      region: "{{ aws_region }}"
      filters:
        "tag:stack": "{{ stack_name }}"
        "tag:UK-SE": "{{ uk_se_name }}"
        "tag:automated": "{{ automation_tool }}"
    register: vpc_facts
  

  - name: OUTPUT VPC ID
    debug:
      msg: "Identified VPC: {{ vpc_facts.vpcs[0].vpc_id }}. This will be deleted."


  - name: DELETE INTERNET GATEWAY
    ec2_vpc_igw:
      vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      state: absent


  - name: DELETE VPC SUBNETS
    ec2_vpc_subnet:
      vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      cidr: "{{ item.value.cidr }}"
      az: "{{ item.value.az }}"
      state: absent
    with_dict: "{{ vpc_subnets }}"


  - name: DELETE ROUTE TABLE
    ec2_vpc_route_table:
      vpc_id: "{{ vpc_facts.vpcs[0].vpc_id }}"
      tags:
        automated: "{{ automation_tool }}"
        stack: "{{ stack_name }}"
        UK-SE: "{{ uk_se_name }}"
      state: absent


  - name: DELETE VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}" 
      state: absent
      cidr_block: "{{ vpc_cidr }}"
      region: "{{ aws_region }}"


#------------------------------------------------------------------------------
# End tasks
#------------------------------------------------------------------------------