- name: PROVISION VPC SUBNETS & F5 INSTANCES
  hosts: localhost
  connection: local
  gather_facts: no

  environment:
    AWS_ACCESS_KEY_ID: "{{ ec2_access_key }}"
    AWS_SECRET_ACCESS_KEY: "{{ ec2_secret_key }}"
    AWS_REGION: "{{ aws_region }}"

#------------------------------------------------------------------------------
# Set variables.
#------------------------------------------------------------------------------

  vars_files:
    - ../../creds.yaml

  vars:

  # SSH
    # This is the name of the SSH private key object in AWS
    sshKey: "arch-key-1"
    # This is the path to your local SSH private key located on your computer
    sshKeyPath:

  # AWS settings
    
    uk_se_name: stephen archer
    stack_name: F5-BIG-IP-LAB
    aws_region: eu-west-2

    vpc_name: "arch_ansible_cft_demo"
    vpc_cidr: "10.3.0.0/16"
    vpc_subnets:
      mgmt_a:
        cidr: 10.3.1.0/24
        az: "{{ aws_region }}a"
      traffic_a:
        cidr: 10.3.11.0/24
        az: "{{ aws_region }}a"



#------------------------------------------------------------------------------
# End variables
#------------------------------------------------------------------------------

  # Start tasks

  tasks:

  - name: DELETE ANSIBLE CFT DEPLOYMENT
    cloudformation:
      stack_name: "ansible-cft-failover-samenet-api-exist-payg"
      state: absent

  - name: remove subnets and route tables from VPC
    local_action:
      module: ec2_vpc
      vpc_id: "{{ vpc.vpc_id }}"
      region: "{{ aws_region }}"
      state: present
      resource_tags: "{}"
      subnets: []
      internet_gateway: False
      route_tables: []
      wait: yes
       
  - name: DELETE ROUTE TABLE FOR PUBLIC SUBNETS
    ec2_vpc_route_table:
      vpc_id: "{{ vpc_id }}"
      route_table_id: "{{ route_table.id }}"
      lookup: id
      state: absent

  - name: DELETE INTERNET GATEWAY
    ec2_vpc_igw:
      vpc_id: "{{ vpc_id }}"
      state: absent
    register: create_gateway

  - name: DELETE VPC SUBNETS
    ec2_vpc_subnet:
      vpc_id: "{{ vpc_id }}"
      cidr: "{{ item.value.cidr }}"
      az: "{{ item.value.az }}"
      tags:
        Name: "{{ item.key }}"
      state: absent
    with_dict: "{{ vpc_subnets }}"
    register: create_vpc_subnets

  - name: DELETE VPC
    ec2_vpc_net:
      name: "{{ vpc_name }}"
      cidr_block: "{{ vpc_cidr }}"
      region: "{{ aws_region }}"
      state: absent
    register: create_vpc



  





